window.songs = [
  {
    songId: "SID-1",
    artistId: "AID-1",
    title: "Case",
    year: "2023",
    
    duration: 129,
    url: "https://www.youtube.com/watch?v=eGuGeKksdVM",
    explicit: false,
    imageUrl: "/src/images/download.jpeg",
  },
  {
    songId: "SID-2",
    artistId: "AID-1",
    title: "Lover",
    year: "2021",
    duration: 181,
    url: "https://www.youtube.com/watch?v=mH_LFkWxpI0",
    explicit: true,
    imageUrl:""
  },
  {
    songId: "SID-3",
    artistId: "AID-1",
    title: "Born to Shine",
    year: "2020",
    duration: 202,
    url: "https://www.youtube.com/watch?v=dCmp56tSSmA",
    explicit: false,
    imageUrl: "/src/images/download (1).jpeg",
  },
  {
    songId: "SID-4",
    artistId: "AID-2",
    title: "Softly",
    year: "2023",
    duration: 150,
    url: "https://www.youtube.com/watch?v=cWMxCE2HTag",
    explicit: false,
    imageUrl: "/src/images/download (6).jpeg",
  },
  {
    songId: "SID-5",
    artistId: "AID-2",
    title: "Try Me",
    year: "2023",
    duration: 189,
    url: "https://www.youtube.com/watch?v=6wkwmDzZ3n4",
    explicit: false,
    imageUrl: "/src/images/download (7).jpeg",
  },
  {
    songId: "SID-6",
    artistId: "AID-2",
    title: "Admirin'You",
    year: "2023",
    duration: 198,
    url: "https://www.youtube.com/watch?v=k85UB5b6pJU",
    explicit: false,
    imageUrl: "/src/images/download (8).jpeg",
  },
  {
    songId: "SID-7",
    artistId: "AID-3",
    title: "With You",
    year: "2023",
    duration: 150,
    url: "https://www.youtube.com/watch?v=mZQH8CPQ-wo",
    explicit: false,
    imageUrl: "/src/images/download (13).jpeg",
  },
  {
    songId: "SID-8",
    artistId: "AID-3",
    title: "True Stories",
    year: "2023",
    duration: 120,
    url: "https://www.youtube.com/watch?v=-wFTG_f-W4c",
    explicit: false,
    imageUrl: "/src/images/download (14).jpeg",
  },
  {
    songId: "SID-9",
    artistId: "AID-3",
    title: "Summer High",
    year: "2022",
    duration: 195,
    url: "https://www.youtube.com/watch?v=nqUN530Rgtw",
    explicit: false,
    imageUrl: "/src/images/download (15).jpeg",
  },
  {
    songId: "SID-10",
    artistId: "AID-1",
    title: "Vibe",
    year: "2021",
    duration: 182,
    url: "https://www.youtube.com/watch?v=fyBzPE6w6-k",
    explicit: false,
    imageUrl: "/src/images/download (2).jpeg",
  },
  {
    songId: "SID-11",
    artistId: "AID-1",
    title: "Do you know",
    year: "2021",
    duration: 203,
    url: "https://www.youtube.com/watch?v=P-DhwN87JDY",
    explicit: false,
    imageUrl: "/src/images/download (3).jpeg",
  },
  {
    songId: "SID-12",
    artistId: "AID-1",
    title: "G.O.A.T",
    year: "2021",
    duration: 205,
    url: "https://www.youtube.com/watch?v=cl0a3i2wFcc",
    explicit: false,
    imageUrl: "/src/images/download (4).jpeg",
  },
  {
    songId: "SID-13",
    artistId: "AID-1",
    title: "Has Has",
    year: "2023",
    duration: 198,
    url: "https://www.youtube.com/watch?v=yF9PX9aeeQM",
    explicit: false,
    imageUrl: "/src/images/hasshass.jpg",
  },
  {
    songId: "SID-14",
    artistId: "AID-2",
    title: "Bachke Bachke",
    year: "2023",
    duration: 198,
    url: "https://www.youtube.com/watch?v=Oqy9KfrdBOc",
    explicit: false,
    imageUrl: "/src/images/download (9).jpeg",
  },
  {
    songId: "SID-15",
    artistId: "AID-2",
    title: "Jee Nai Lagda",
    year: "2023",
    duration: 131,
    url: "https://www.youtube.com/watch?v=BXNxrT59MzQ",
    explicit: false,
    imageUrl: "/src/images/download (10).jpeg",
  },
  {
    songId: "SID-16",
    artistId: "AID-2",
    title: "Take it easy",
    year: "2022",
    duration: 197,
    url: "https://www.youtube.com/watch?v=Guq9Vl8dK30",
    explicit: false,
    imageUrl: "/src/images/download (11).jpeg",
  },
  {
    songId: "SID-17",
    artistId: "AID-2",
    title: "Players",
    year: "2023",
    duration: 150,
    url: "https://www.youtube.com/watch?v=CeFQO9MQNqs",
    explicit: false,
    imageUrl: "/src/images/download (12).jpeg",
  },
  {
    songId: "SID-18",
    artistId: "AID-3",
    title: "Dil Nu",
    year: "2022",
    duration: 211,
    url: "https://www.youtube.com/watch?v=p2EdDiiVHh4",
    explicit: false,
    imageUrl: "/src/images/download (16).jpeg",
  },
  {
    songId: "SID-19",
    artistId: "AID-3",
    title: "Insane",
    year: "2021",
    duration: 193,
    url: "https://www.youtube.com/watch?v=cqP8I5aaud8",
    explicit: false,
    imageUrl: "/src/images/download (17).jpeg",
  },
  {
    songId: "SID-20",
    artistId: "AID-3",
    title: "Brown Munde",
    year: "2020",
    duration: 256,
    url: "https://www.youtube.com/watch?v=VNs_cCtdbPc",
    explicit: false,
    imageUrl: "/src/images/download (18).jpeg",
  },
  {
    songId: "SID-21",
    artistId: "AID-3",
    title: "Desires",
    year: "2021",
    duration: 132,
    url: "https://www.youtube.com/watch?v=3ONzh3tf884",
    explicit: true,
    imageUrl: "/src/images/download.jpeg",
  },
  {
    songId: "SID-22",
    artistId: "AID-1",
    title: "Ghost",
    year: "2023",
    duration: 165,
    url: "https://www.youtube.com/watch?v=IKeYqqZ1cFg",
    explicit: false,
    imageUrl: "/src/images/download (5).jpeg",
  },
];
